services:
  postgres:
    image: postgres
    container_name: rhproject
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'
    volumes:
      - rhproject_data:/var/lib/postgresql/data

volumes:
  rhproject_data:
